pilot version

diff --git a/.github/actions/deploy/action.yml b/.github/actions/deploy/action.yml
--- a/.github/actions/deploy/action.yml
+++ b/.github/actions/deploy/action.yml
@@ -124,14 +124,17 @@ runs:
 
             sudo systemctl restart "$SERVICE"
 
-            if systemctl list-unit-files | grep -q "^$CELERY_FILE"; then
+            if sudo systemctl list-unit-files | grep -q "^$CELERY_FILE"; then
               sudo systemctl restart "$CELERY_SERVICE"
             fi
 
             echo "Rollback completed."
           }
 
-          trap 'rollback' ERR
+          trap 'echo ""; \
+            echo "FAILED COMMAND: $BASH_COMMAND"; \
+            echo "LINE: $LINENO"; \
+            rollback' ERR
 
           echo "Backing up current systemd service files..."
 
@@ -170,7 +173,7 @@ runs:
           sudo systemctl restart "$SERVICE"
 
           echo "Restarting Celery service..."
-          if systemctl list-unit-files | grep -q "^$CELERY_FILE"; then
+          if sudo systemctl list-unit-files | grep -q "^$CELERY_FILE"; then
             sudo systemctl restart "$CELERY_SERVICE"
           fi
 
